/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_omniagent_mobile_NativeEngineJNI */

#ifndef _Included_io_omniagent_mobile_NativeEngineJNI
#define _Included_io_omniagent_mobile_NativeEngineJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_omniagent_mobile_NativeEngineJNI
 * Method:    initEngine
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_io_omniagent_mobile_NativeEngineJNI_initEngine
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     io_omniagent_mobile_NativeEngineJNI
 * Method:    generateText
 * Signature: (JLjava/lang/String;F)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_omniagent_mobile_NativeEngineJNI_generateText
  (JNIEnv *, jobject, jlong, jstring, jfloat);

/*
 * Class:     io_omniagent_mobile_NativeEngineJNI
 * Method:    freeEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_omniagent_mobile_NativeEngineJNI_freeEngine
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
